services:
  sender:
    env_file:
      - .env
    container_name: sender
    build: ./backend/sender/
    ports:
      - "5000:5000"
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
  frontend:
    container_name: frontend
    build: ./frontend/
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200
