services:
  sender:
    container_name: sender
    build: ./backend/sender/
    ports:
      - "5000:5000"
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
  
  frontend:
    container_name: frontend
    build: ./frontend/
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200
  
  parser:
    container_name: parser
    build: ./backend/parser/
    ports:
      - "8888:8888"
    depends_on:
      - db_parse_results
    environment:
      - PARSER_DB_HOST=${PARSER_DB_HOST}
      - PARSER_DB_PORT=5432
      - PARSER_DB_NAME=${PARSER_DB_NAME}
      - PARSER_DB_USER=${PARSER_DB_USER}
      - PARSER_DB_PASSWORD=${PARSER_DB_PASSWORD}
  
  db_parse_results:
    image: postgres:13
    container_name: ${PARSER_DB_HOST}
    environment:
      POSTGRES_DB: ${PARSER_DB_NAME}
      POSTGRES_USER: ${PARSER_DB_USER}
      POSTGRES_PASSWORD: ${PARSER_DB_PASSWORD}
    ports:
      - "5432:5432"
