version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DB_API_CONN=sqlite:///./internship.sqlite  # Убедитесь, что путь правильный
    command: flask run --host=0.0.0.0
